### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by walshe** [ajmath/serverless-offline-scheduler#17]
does it have issue with es6/7 ?

`export const job = async (event, context, callback) => {
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)`

**Comment by ajmath** [comment]
This looks like a problem with the node version that serverless is executing under not knowing how to interpret your handler source.  Could you provide some more details?

**Comment by walshe-boylesoftware** [comment]
when I changed it to "module.exports.job = ".. it worked

would be nice for it to support newer versions of ecma script though
